---

- name: NGINX | Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: NGINX | Manage RedHat environment
  import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: NGINX | Installation
  package:
    name: nginx
    state: present

- name: NGINX | Configuration
  template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart nginx

- name: NGINX | Delete the default directory and site
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/www/html
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/conf.d/default
  notify: Reload nginx
