- name: Restart nginx
  systemd:
    name: nginx
    state: restarted

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: Reload systemd + Restart nginx
  systemd:
     name: nginx
     state: restarted
     daemon_reload: yes
